# Generated by Django 5.1.4 on 2025-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_song_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
