# Generated by Django 5.1.4 on 2025-01-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_playlist_rating_songcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='songcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.song'),
        ),
    ]
